### ISSUE TITLE
совместимость с новой OpenCart 2.1.0.1?

### ISSUE THREAD

**Issue by neccospb** [ulogin/ulogin-OpenCart#1]
Cпасибо за отличную работу, это лучший модуль к лучшему сервису! 
Но есть ли в планах доработка до совместимости с последней OpenCart 2.1.0.1? 

При попытке включить модуль выдает: Notice: Error: Could not load model .../admin/model/sale/customer_group.php! in ...\system\storage\modification\system\engine\loader.php on line 74

Ждем обновлений, заранее спасибо!

**Comment by ulogin-team** [comment]
Прямо сейчас, к сожалению, не хватает свободных рук( 
Но не будем затягивать и постараемся побыстрее выпустить обновление.

**Comment by lyolic** [comment]
Очень ждем!!!! Спасибо!

**Comment by varanakonda** [comment]
Ждём с нетерпением!

**Comment by Timur-Samatov** [comment]
Поддерживаю! Очень ждем!!!

**Comment by SP86** [comment]
Плагин очень хороший. Все вроде бы хорошо работает но заметил один нюанс. Когда покупателя в системе не существует то используя Ваш плагин не происходит редирект в личный кабинет. Если нажать F5 то страница обновляется и я попадаю в личный кабинет уже под своей учетной записью. И последующий вход и выход работает как часы (поскольку пользователь уже создан). Такая проблема я понимаю не только у меня (http://forum.opencart-russia.ru/threads/avtorizacija-ulogin.380/) но ее так никто и не решил.

**Comment by Timur-Samatov** [comment]
Други, проверье в файле /upload/admin/controller/module/ulogin_sets.php заменить все слова sale на customer. Закачать и установить. У меня вроде работает!

**Comment by SP86** [comment]
Открыл файл upload/admin/controller/module/ulogin_sets.php. Например в этом файле есть строка подключения модели $this->load->model('sale/customer_group');
Если мы заменим слово sale на customer то мы не сможем подключить эту модель поскольку в opencart есть каталог sale но нету каталога customer в моделях админ части. Или я не прав?
и 100% вылезут ошибки. например такая Could not load model /var/www/мой-сайт.ру/admin/model/customer/customer_group.php!

**Comment by Timur-Samatov** [comment]
в 2.1.0.1 наоборот в нет sale/customer_group.php, а есть customer/customer_group.php
Все равно этого было не достатчно, поторопился с выводом. При установке не ругается, но виждета так и не вижу.

**Comment by ulogin-team** [comment]
https://github.com/ulogin/ulogin-OpenCart/commit/8cf47af8db5c3167bea45f8ac36afedf41a38630

Спасибо coolloki за предложенное решение. Потребовалось только чуть улучшить для совместимости со старыми версиями.

**Comment by SP86** [comment]
Для opencart 2.0.3.1 все же не работает. Выдает Call to a member function getCustomerGroups() on a non-object in ..... admin/controller/module/ulogin_sets.php on line 102. 
($groups = $this->model_customer_customer_group->getCustomerGroups();)

Все тот же каталог customer в моделях которого в opencart 2.0.3.1 нету. ))

**Comment by ulogin-team** [comment]
А я еще один коммит выпустил несколько минут назад, в котором исправил этот недочет. Попробуйте его, пожалуйста.

**Comment by SP86** [comment]
Я так понимаю речь идет о коммите 758c9a3. Я внес эти правки. Ошибку при активации модулей действительно не выдало но проблема осталась. Когда покупателя в системе не существует то не происходит редирект в личный кабинет. После нажатия f5 попадаю в личный кабинет уже залогиненым.

**Comment by ulogin-team** [comment]
В этой ветке идет речь о совместимости с версией 2.1.0.1. Но если хотите - хорошо, давайте обсудим и вашу проблему... 
Откройте панель разработчика в хроме, воспроизведите свою ситуацию и посмотрите какой запрос ушел при регистрации и какой ответ в нем вернулся.

**Comment by SP86** [comment]
Изначально в консоле пишет 
-[uLogin] ulogin.js received message: ready
Нажимаю кнопку соц-сети. В консоле появилось
-[uLogin] ulogin.js received message: open
-[uLogin] ulogin.js received message: uloginCallback(03df82beb578ee04dff93007fe25409a)
-XHR finished loading: POST "http://shirt-test.nashinadra.com/index.php?route=module/ulogin/login".
--k.cors.a.crossDomain.send @ jquery-2.1.1.min.js:4
--n.extend.ajax @ jquery-2.1.1.min.js:4
--uloginCallback @ ulogin.js:37
--easyXDM.Socket.onMessage @ ulogin.js:62
--ba.concat.incoming @ ulogin.js:16
--f @ ulogin.js:23

Но остаюсь на index.php?route=account/login
Нажимаю F5. Перехожу на index.php?route=account/account уже под аккаунтом.

**Comment by ulogin-team** [comment]
Вывод консоли неинтересен. Запрос посмотрите на вкладке networks. Вот этот самый " ****?route=module/ulogin/login" который упоминается в консоли. И нужен response этого запроса: скрин https://drive.google.com/file/d/0B2IQYa2K6pa0Qk1rLVYyMWxUMWs/view?usp=drivesdk

**Comment by SP86** [comment]
После нажатия на иконку соц-сети для запроса route=module/ulogin/login ответ вот такой http://prntscr.com/99gnbn.

**Comment by ulogin-team** [comment]
Отлично, вот это то что нужно. Пробуйте новый коммит. 
Хочется еще отметить, что на боевом сайте вывод подобных сообщений (Notice & Warning) должен быть выключен, чтобы не возникало подобных ситуаций и чтобы пользователи не видели лишний раз подобных ошибок.

**Comment by SP86** [comment]
Сейчас действительно все заработало. Спасибо огромное за помощь.

**Comment by lyolic** [comment]
В ряде тем, если модуль активирован то плывет(съезжает вниз) страница логина:
![default](https://cloud.githubusercontent.com/assets/12529079/11609783/4adb9926-9ba1-11e5-9d05-e5304274b854.png)
