### ISSUE TITLE
Проблема со входом с iPhone 4s

### ISSUE THREAD

**Issue by max-solovey** [ulogin/ulogin-OpenCart#10]
Здравствуйте, обнаружил проблему при попытке войти через соцсети с 4S - вначале авторизация проходит - а затем редирект на страницу https://ulogin.ru/login и дальше ловлю 404 ошибку от nginx'а. Сайт на Yii 1.1.15. С компьютера авторизируюсь без проблем. Заранее благодарен. Адрес сайта - http://internetshop.in.ua/ - форма входа в правом верхнем углу шапки.

![image](https://cloud.githubusercontent.com/assets/22969631/19582097/90a9fab6-973a-11e6-8055-80e3aa8b1780.png)

**Comment by ipshenicyn** [comment]
Здравствуйте.
У вас в настрйоках виджета указан некорректный параметр redirect_uri. Он должен быть абсолютным путем, а не относительным.

**Comment by max-solovey** [comment]
Спасибо огромное, прараметр подставлял да не туда. Впилил хардкодом в представление виджета, заработало. Извините что побеспокоил по столь банальной мелочи, поздней ночью пилил, думалки не хватило, хотя был очень близко. Удачи Вам и вашему бизнесу.

21 октября 2016, 09:33:45, от Ivan Pshenitsyn :
