### ISSUE TITLE
На 2.3 неправильный

### ISSUE THREAD

**Issue by bliketto** [ulogin/ulogin-OpenCart#13]
Таких каталогов в 2.3 нет:
catalog/language/ru/
admin/language/ru/

Кликаем в админке в хлебных крошках на "Модули" находясь в Модули -> uLogin - панель и получаем "Доступ запрещен!
У Вас нет прав для доступа к этой странице. Если она Вам нужна, обратитесь к администратору."

**Comment by ipshenicyn** [comment]
Простите, не понял о чем речь. 
Для начала: речь о ветке плагина для версии 2.3+? 
Указанные каталоги ни разу не упоминаются в коде плагинов на обоих ветках. Что это вообще за каталоги, откуда это?
В крошках все работает на моей тестовой версии опенкарт 2.3.* https://goo.gl/1cHcrr

**Comment by bliketto** [comment]
http://imgur.com/a/JaGFX
http://imgur.com/a/MuyDl

**Comment by ipshenicyn** [comment]
Спасибо. Проблему с крошками поправили.
