### ISSUE TITLE
Ручное размещение виджета.

### ISSUE THREAD

**Issue by assada** [ulogin/ulogin-OpenCart#4]
Интересный факт. При ручном размещении виджета не добавляет ассеты на страницу(css, js).
Див есть, а ассетов нет.

**Comment by assada** [comment]
Решение оказалось простым. Нужно добавлять 

``` php
$data['ulogin_form_marker'] = $this->load->controller('module/ulogin');
```

в самое начало метода, а не в конец(как делал я).

**Comment by assada** [comment]
Однако есть другая проблема. 
Если аккаунт с таким email не существует плагин не регистрирует новый аккаунт. Просто закрывается oauth окно и все.

**Comment by ipshenicyn** [comment]
Спасибо за уточнение насчет размещения кода в начало метода. Мы сами совсем недавно сделали это открытие, но посчитали, что одного раза мало, чтобы делать выводы. 
Теперь добавим уточнение в ридми. 

По поводу регистрации нового аккаунта: пользователи, разумеется, должны регистрироваться. Мы пока не слышали о подобной проблеме. Назовите, пожалуйста, адрес сайта, где можно посмотреть. Попробуем сами и проверим настройки виджета. Пишите на team@ulogin.ru

**Comment by assada** [comment]
Все оказалось проще. Я реализовал подтверждение email`а для новых пользователей и на домашней локальной машине забыл накатить миграции(нужно в composer добавить post-script для phinx`а =) ). Вот и INSERT при регистрации не проходил в методе catalog/model/account/customer.php:8 -> addCustomer()
