### ISSUE TITLE
совместимость oс 2.1.0.2 + Journal 2.7.3

### ISSUE THREAD

**Issue by neccospb** [ulogin/ulogin-OpenCart#5]
Активируется без ошибок, панели создаются, но вместо вывода вижу только "Войти с помощью" и пустое место. Использую сторонний шаблон Journal. На родном шаблоне форма видна..

из системного лога:
2016-06-15 20:57:51 - PHP Notice:  Undefined variable: entry_status in ..\admin\view\template\module\ulogin_sets.tpl on line 65
2016-06-15 20:57:51 - PHP Notice:  Undefined variable: ulogin_sets_status in ..\admin\view\template\module\ulogin_sets.tpl on line 68

**Comment by ipshenicyn** [comment]
Здравствуйте. 
Дело, скорее всего, не в совместимости. Просто в вашем шаблоне плагин не смог вывести виджет. Это обычное дело. Гарантировать показ виджета в любом шаблоне невозможно. 
Вам нужно только воспользоваться инструкцией и добавить вывод виджета в нужное место шаблона вручную. 

Что касается записей в логе, то они, очевидно, не связаны с показом виджета, т.к. указывают на файлы админской части шаблона. А т.к. сообщения не говорят об ошибках, скорее всего они никоим образом не влияют на работу плагина. Вообще, сообщения очень странные, учитывая, что указывают на закомменченные участки кода. Возможно, шаблонизатор не понимает таких комментариев. В любом случае, мы удалим этот ненужный участок кода, если он не несет никакой смысловой нагрузки.
