### ISSUE TITLE
При попытке входа с телефона (iphone 5)  через любую соц. сеть идет постоянный редирект и ничего не происходит

### ISSUE THREAD

**Issue by ilerok17** [ulogin/ulogin-OpenCart#6]
Исправрьте пожалуйста, при попытке входа с телефона (iphone 5)  через любую соц. сеть идет постоянный редирект и ничего не происходит.

С компьютера все ок.

**Comment by ulogin-team** [comment]
Скорее всего, данная проблема наблюдается только на вашем сайте. Причем, судя по всему, проблема именно в поведении вашего сайта. Назовите адрес, посмотрим и скажем, что нужно исправить.

**Comment by ilerok17** [comment]
Добрый день, вот сайт: http://conversionweb.ru/ кнопки авторизации можете увидеть в всплывающем окне нажав на "войти" в правой верхней части сайта. 

Вот скриншот: http://prntscr.com/bw0r87 

Работает все на opencart 2. Ну и естественно проверять надо с телефона.

**Comment by ulogin-team** [comment]
Спасибо, нашли проблему. 
Простите, ошибка действительно у нас (хотя симптомы изначально указывали на другой случай). Исправим в ближайшее время, пара часов - максимум. 
После исправления отпишемся здесь.

**Comment by ulogin-team** [comment]
Исправили ошибку в своем скрипте. Ошибка была не в плагине, поэтому вам не нужно обновлять файлы. 
Через несколько минут, пожалуйста, обновите кеш браузера и проверьте работу.

**Comment by ilerok17** [comment]
Спасибо, исправилось.
