### ISSUE TITLE
Security errors using with Opencart 2.3.0.2

### ISSUE THREAD

**Issue by pavlo-tk** [ulogin/ulogin-OpenCart#9]
Hello, I'm using 2.3+ branch with Opencart 2.3.0.2 and having following javascript error in browser's console in file that loaded from https://ulogin.ru/version/2.0/js/drop.js?1:
    **Firefox** — “SecurityError: The operation is insecure.” at drop.js:2:0
    **Chrome** — “Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.”

In UI dropdown is empty:
![2016-09-23_17-57-55](https://cloud.githubusercontent.com/assets/7204866/18790413/59d69302-81b7-11e6-9e61-22c4f22595c4.png)

**Comment by ipshenicyn** [comment]
Please, check the "privacy settings" in your browsers. For example, like this https://goo.gl/2JC8ZZ

**Comment by pavlo-tk** [comment]
Thanks for the tip.
It was “**Block third-party cookies and site data**” checkbox and the same in Firefox. By default these checkboxes are not set, so I suppose most of users will not face this problem.

Thank you again, I fully forgot about this setting,
